### ISSUE TITLE
聊天机器人扫码登录失败，是我个人账号的问题吗？不知道题主的还能用吗

### ISSUE THREAD

**Issue by jy007** [inspurer/PythonLearning#1]
Your wechat account may be LIMITED to log in WEB wechat, error info:
<error><ret>1203</ret><message>为了你的帐号安全，此微信号已不允许登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com</message></error>

**Comment by inspurer** [comment]
几乎所有账号都这样
